#!/bin/sh

# this file was generated by mas2j parser

echo -n "        compiling user classes..."
javac -classpath .:"/Users/jomi/programming/agents/Jason/bin/jason.jar":"/Users/jomi/programming/agents/Jason/lib/saci/bin/saci.jar":"/Users/jomi/programming/agents/Jason/examples/Simple":"$CLASSPATH"  myPkg/*.java


echo ok
