#!/bin/sh

# this file was generated by mas2j parser

java -classpath .:"/Users/jomi/programming/agents/Jason/bin/jason.jar":"/Users/jomi/programming/agents/Jason/lib/saci/bin/saci.jar":"/Users/jomi/programming/agents/Jason/examples/Simple":"$CLASSPATH" jIDE.RunCentralisedMAS "testCent.xml"
