#!/bin/sh

# this file was generated by mas2j parser

java -classpath .:"/Users/jomi/programming/agents/Jason/bin/jason.jar":"/Users/jomi/programming/agents/Jason/bin/../lib/saci/bin/saci.jar":"/Users/jomi/programming/agents/Jason/examples/Robot":"$CLASSPATH" jIDE.RunCentralisedMAS "marsCent.xml"
